---
groups:
- name: main
  jobs:
  - husky

resources:
- name: example
  type: git
  source:
    branch: master
    uri: https://github.com/molambo/example
   
jobs:
- name: husky 
  plan:
  - get: example
  - task: example-task
    file: example/task.yml

      
 
